name: navigation
description: "A new Flutter package project."
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

dependencies:
  auto_route: ^10.1.0+1

  flutter:
    sdk: flutter
  core:
    path: ../core

  character_list:
    path: ../features/character_list

  detailed_character:
    path: ../features/detailed_character

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.3
