name: detailed_character
description: "A new Flutter package project."
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  navigation:
    path: ../../navigation

  core:
    path: ../../core

  domain:
    path: ../../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.3